//BOOK INFORMATION
package Info;

import Interface.*;
import Books.Bookinfo;
import Books.SavedBooks;
import static Books.SavedBooks.books;
import static Interface.Administrator.loadData;
import java.util.TreeMap;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class BookInformation1 extends javax.swing.JFrame {

    
    /**
     * Creates new form BookInformation
     */
    public BookInformation1() {
        initComponents();
        this.setSize(600, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(libro1, "src/Images/el nombre del viento.jpg");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Jauthor = new javax.swing.JTextField();
        JTitlespot = new javax.swing.JTextField();
        libro1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sinopsis:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        Jauthor.setBackground(new java.awt.Color(255, 255, 255));
        Jauthor.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        Jauthor.setForeground(new java.awt.Color(102, 102, 102));
        Jauthor.setText("Patrick Rothfuss");
        Jauthor.setBorder(null);
        Jauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JauthorActionPerformed(evt);
            }
        });
        jPanel1.add(Jauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 20));

        JTitlespot.setBackground(new java.awt.Color(255, 255, 255));
        JTitlespot.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        JTitlespot.setForeground(new java.awt.Color(51, 51, 51));
        JTitlespot.setText("El nombre del Viento");
        JTitlespot.setBorder(null);
        JTitlespot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTitlespotActionPerformed(evt);
            }
        });
        jPanel1.add(JTitlespot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, -1));

        libro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(libro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 190));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane1.setText("La historia de Kvothe comienza en los años de \nsu infancia como miembro de una familia de artistas itinerantes, \nlos Edena Ruh, formada por músicos, actores, acróbatas y \njuglares. En este ambiente crece convirtiéndose en un niño \nprodigio para la música y los cuentos, alegre \ny diplomático.");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 310, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JauthorActionPerformed

    private void JTitlespotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTitlespotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTitlespotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInformation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInformation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInformation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInformation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookInformation1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTitlespot;
    private javax.swing.JTextField Jauthor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel libro1;
    // End of variables declaration//GEN-END:variables
}
